### ISSUE TITLE
Use state names as variables

### ISSUE THREAD

**Issue by nmde** [idaholab/EMRALD#180]
Using state names as variables is currently implemented, but causes issues when special characters are used in state names that cause compilation errors when trying to run code. The temporary solution is to remove the state names from the code entirely, but it would be nice to still have access to that feature in some way.

**Comment by pressr-inl** [comment]
Added to MAAP branch. It adds them if specified in the code and the name doesn't have any special chars. Also has a timespan variable available for when that state was entered called [name]_Time.
