### ISSUE TITLE
Cant open the following attached model in EMRALD

### ISSUE THREAD

**Issue by ramsampath** [idaholab/EMRALD#50]
Even though it works in the Simulator - this json input cant seem to be opened in the web GUI.
[Sim20.md](https://github.com/idaholab/EMRALD/files/6897450/Sim20.md)

**Comment by nmde** [comment]
It looks like that file isn't valid JSON, it has a stray comma on line 46. Where was this file saved from? If it was saved from the EMRALD UI, I'll fix the file generation, but if it's from anywhere else I'll need come up with some kind of workaround.
